import Foundation

/// Kinds of agent-produced artifacts the iOS detail view knows how to
/// render. Anything outside this set is dropped by the runner's parser
/// (`parse_artifacts` in `runner/runner/events.py`) so we never store rows
/// the UI can't display.
enum ArtifactKind: String, Codable, Sendable, CaseIterable {
    case link
    case email
    case calendar
    case text
    /// Spoken summary generated by Hermes' `text_to_speech` tool, uploaded
    /// to the private `todo-audio` Supabase Storage bucket. Renders as an
    /// AVPlayer-backed card at the top of the detail view with the long-
    /// form spoken text shown underneath the controls.
    case audio
}

/// One user-visible deliverable produced by the agent — a created Google
/// Sheet/Doc link, a sent email summary, a calendar invite, or a short
/// text result. Multiple artifacts can sit on a single todo and the agent
/// is allowed to update one in place by re-emitting it with the same
/// `artifact_key`.
///
/// The shape of `payload` depends on `kind`; the computed accessors below
/// pull common fields out so call sites don't have to dig through the
/// `JSONValue` tree.
struct TodoArtifact: Codable, Identifiable, Hashable, Sendable {
    let id: UUID
    let todo_id: UUID
    let user_id: UUID
    let artifact_key: String
    let kind: ArtifactKind
    let title: String?
    let payload: JSONValue?
    let hermes_run_id: String?
    let created_at: Date
    let updated_at: Date

    // MARK: - Shared helpers

    /// Convenience accessor for the payload's top-level object, since
    /// every render path needs it.
    private var object: [String: JSONValue]? { payload?.objectValue }

    /// Truthy when the artifact has at least enough data to render
    /// something useful. Used to defensively skip empty rows.
    var hasContent: Bool {
        switch kind {
        case .link: return url != nil
        case .email: return emailDraft != nil
        case .calendar: return calendarEvent != nil
        case .text: return !(text ?? "").isEmpty
        case .audio: return audio != nil
        }
    }

    // MARK: - link

    /// `payload.url` parsed as a `URL` for link artifacts (and used as the
    /// "open in browser" target for calendar artifacts that also carry
    /// one).
    var url: URL? {
        guard let raw = object?["url"]?.stringValue else { return nil }
        return URL(string: raw)
    }

    /// Toolkit slug the link came from (e.g. `googlesheets`, `googledocs`,
    /// `gmail`). Drives the small leading icon on the link card; falls
    /// back to a generic glyph when absent.
    var provider: String? {
        object?["provider"]?.stringValue
    }

    /// Composio slug for email drafts (defaults to `gmail`).
    var emailProvider: String {
        let raw = object?["provider"]?.stringValue?.trimmingCharacters(in: .whitespacesAndNewlines)
        if let raw, !raw.isEmpty { return raw.lowercased() }
        return "gmail"
    }

    // MARK: - email

    /// `(subject, body, to)` triple for email artifacts. Returns nil when
    /// the payload doesn't look like a structured draft, so call sites can
    /// fall back to a generic renderer.
    var emailDraft: (subject: String, body: String, to: [String])? {
        guard let obj = object else { return nil }
        guard let subject = obj["subject"]?.stringValue,
              let body = obj["body"]?.stringValue else { return nil }
        let to = obj["to"]?.arrayValue?.compactMap { $0.stringValue } ?? []
        return (subject: subject, body: body, to: to)
    }

    // MARK: - calendar

    /// Parsed view of a calendar artifact. `start`/`end` are decoded from
    /// ISO 8601 strings; both are optional so a half-specified event
    /// still renders the parts it does have.
    struct CalendarEvent: Hashable, Sendable {
        let title: String
        let start: Date?
        let end: Date?
        let location: String?
        let attendees: [String]
        let url: URL?
    }

    var calendarEvent: CalendarEvent? {
        guard let obj = object else { return nil }
        let title = obj["title"]?.stringValue ?? self.title
        guard let title, !title.isEmpty else { return nil }
        let attendees = obj["attendees"]?.arrayValue?
            .compactMap { $0.stringValue } ?? []
        let urlValue = obj["url"]?.stringValue.flatMap(URL.init(string:))
        return CalendarEvent(
            title: title,
            start: obj["start"]?.stringValue.flatMap(Self.parseISO8601),
            end: obj["end"]?.stringValue.flatMap(Self.parseISO8601),
            location: obj["location"]?.stringValue,
            attendees: attendees,
            url: urlValue
        )
    }

    // MARK: - text

    /// Plain-text body for `kind == .text` artifacts.
    var text: String? { object?["text"]?.stringValue }

    // MARK: - audio

    /// Parsed view of an `audio` artifact. The bytes live in the private
    /// `todo-audio` Supabase Storage bucket; the UI signs `storagePath`
    /// on demand to get a short-lived URL it can feed to `AVPlayer`.
    /// `text` is the spoken transcript the player renders underneath
    /// its controls so the user can read while they listen (or instead).
    struct AudioClip: Hashable, Sendable {
        let bucket: String
        let storagePath: String
        let mimeType: String?
        let provider: String?
        let voice: String?
        let text: String?
        let durationSeconds: Double?
        let byteSize: Int?
    }

    /// Parsed audio payload (only populated when `kind == .audio`).
    /// Returns `nil` when the row is missing the required
    /// `storage_path`, which guards against malformed runner writes.
    var audio: AudioClip? {
        guard let obj = object else { return nil }
        guard let path = obj["storage_path"]?.stringValue,
              !path.isEmpty else { return nil }
        let bucket = obj["bucket"]?.stringValue ?? "todo-audio"
        let mime = obj["mime_type"]?.stringValue
        let provider = obj["provider"]?.stringValue
        let voice = obj["voice"]?.stringValue
        let text = obj["text"]?.stringValue
        let duration = obj["duration_seconds"]?.numberValue
        let byteSize: Int? = obj["byte_size"]?.numberValue.map { Int($0) }
        return AudioClip(
            bucket: bucket,
            storagePath: path,
            mimeType: mime,
            provider: provider,
            voice: voice,
            text: text,
            durationSeconds: duration,
            byteSize: byteSize
        )
    }

    // MARK: - Internals

    /// ISO 8601 parser that accepts both the fractional-second variant
    /// (`2025-06-01T12:00:00.000Z`) and the plain one (`2025-06-01T12:00:00Z`).
    /// Returns nil when neither shape matches; callers render the raw
    /// string as a fallback when this happens.
    private static func parseISO8601(_ raw: String) -> Date? {
        let trimmed = raw.trimmingCharacters(in: .whitespaces)
        if let d = isoFractional.date(from: trimmed) { return d }
        return isoBasic.date(from: trimmed)
    }

    private static let isoFractional: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    private static let isoBasic: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()
}

// MARK: - Detail header layout

extension TodoArtifact {
    /// Primary deliverables (sheet, doc, calendar, text) first; email drafts
    /// grouped underneath so the header reads as a drill-down. Audio
    /// summaries always come first in the primary group so the player
    /// sits at the very top of the detail view, regardless of when it
    /// was emitted relative to other deliverables.
    static func groupedForDisplay(
        _ artifacts: [TodoArtifact]
    ) -> (primary: [TodoArtifact], emailDrafts: [TodoArtifact]) {
        let sorted = artifacts.sorted {
            if $0.created_at != $1.created_at { return $0.created_at < $1.created_at }
            return $0.artifact_key < $1.artifact_key
        }
        let deduped = deduplicatedForDisplay(sorted)
        let audio = deduped.filter { $0.kind == .audio }
        let others = deduped.filter { $0.kind != .email && $0.kind != .audio }
        let primary = audio + others
        let emails = deduped.filter { $0.kind == .email }
        return (primary, emails)
    }

    /// Collapse repeated artifact rows that refer to the same user-facing
    /// deliverable. Reruns can emit a fresh row/key while updating an
    /// existing calendar invite or email draft; the header should keep the
    /// original card position and render the newest row's content.
    private static func deduplicatedForDisplay(_ sorted: [TodoArtifact]) -> [TodoArtifact] {
        var buckets: [String: ArtifactDisplayBucket] = [:]

        for artifact in sorted {
            let identity = artifact.displayIdentity
            if var bucket = buckets[identity] {
                if artifact.updated_at >= bucket.artifact.updated_at {
                    bucket.artifact = artifact
                }
                if artifact.created_at < bucket.firstCreated {
                    bucket.firstCreated = artifact.created_at
                    bucket.firstKey = artifact.artifact_key
                }
                buckets[identity] = bucket
            } else {
                buckets[identity] = ArtifactDisplayBucket(
                    firstCreated: artifact.created_at,
                    firstKey: artifact.artifact_key,
                    artifact: artifact
                )
            }
        }

        return buckets.values
            .sorted {
                if $0.firstCreated != $1.firstCreated {
                    return $0.firstCreated < $1.firstCreated
                }
                return $0.firstKey < $1.firstKey
            }
            .map(\.artifact)
    }

    private var displayIdentity: String {
        switch kind {
        case .calendar:
            if let event = calendarEvent {
                return [
                    "calendar",
                    Self.normalized(event.title),
                    Self.dateIdentity(event.start),
                    Self.dateIdentity(event.end)
                ].joined(separator: "|")
            }
        case .email:
            if let draft = emailDraft {
                return [
                    "email",
                    emailProvider,
                    draft.to.map(Self.normalized).sorted().joined(separator: ","),
                    Self.normalized(draft.subject)
                ].joined(separator: "|")
            }
        case .link:
            if let url {
                return "link|\(url.absoluteString.lowercased())"
            }
        case .text:
            return [
                "text",
                Self.normalized(title ?? ""),
                Self.normalized(text ?? "")
            ].joined(separator: "|")
        case .audio:
            if let clip = audio {
                return "audio|\(clip.storagePath)"
            }
        }

        return "\(kind.rawValue)|\(artifact_key)"
    }

    private static func normalized(_ value: String) -> String {
        value
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(
                of: #"\s+"#,
                with: " ",
                options: .regularExpression
            )
            .lowercased()
    }

    private static func dateIdentity(_ value: Date?) -> String {
        guard let value else { return "" }
        return String(Int(value.timeIntervalSince1970))
    }

    /// Connection logos for the metadata row: prep slug first, then providers
    /// discovered from artifacts as the task progresses.
    static func connectionSlugs(
        todoSlug: String?,
        artifacts: [TodoArtifact]
    ) -> [String] {
        var seen = Set<String>()
        var result: [String] = []

        func add(_ raw: String?) {
            guard let raw else { return }
            let slug = raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            guard !slug.isEmpty, !seen.contains(slug) else { return }
            seen.insert(slug)
            result.append(slug)
        }

        add(todoSlug)
        let (primary, emails) = groupedForDisplay(artifacts)
        for artifact in primary {
            // Audio artifacts carry a TTS provider name (elevenlabs, openai,
            // edge, …) rather than a Composio toolkit slug, so they would
            // render as a missing logo. Skip them — the player itself
            // already shows the provider as a small pill.
            guard artifact.kind != .audio else { continue }
            add(artifact.provider)
        }
        for artifact in emails {
            add(artifact.emailProvider)
        }
        return result
    }
}

private struct ArtifactDisplayBucket {
    var firstCreated: Date
    var firstKey: String
    var artifact: TodoArtifact
}
